version: '3'
services:
  api:
    build:
      context: ./api
    image: equation-solver-api
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    networks:
      - equation-solver
    environment: 
      API_URL: api

  frontend:
    build:
      context: ./frontend
    image: equation-solver-frontend
    command: ["serve", "-s", "build"]
    ports:
      - "3000:3000"
    networks:
      - equation-solver
    environment: 
      API_URL: api

networks:
  equation-solver:
    driver: bridge
